#!/usr/bin/env bash
# Configure your domain zone

display_subdomain_info() {
  local domain="$1"
  local subdomain="$2"
  local result=$(dig +short "$subdomain.$domain")

  if [[ -n "$result" ]]; then
    local record_type=$(dig +short -t "$subdomain.$domain" | awk 'NR==1{print $4}')
    echo "The subdomain $subdomain is a $record_type record and points to $result"
  else
    echo "No records found for subdomain $subdomain"
  fi
}
main() {
  local domain="$1"
  local subdomain="$2"
  subdomains=("www" "lb-01" "web-01" "web-02")

  if [[ -z "$subdomain" ]]; then
    for sub in "${subdomains[@]}"; do
      display_subdomain_info "$domain" "$sub"
    done
  else
    display_subdomain_info "$domain" "$subdomain"
  fi
}
if [[ $# -eq 2 ]]; then
  main "$1" "$2"
else
  echo "Usage: $0 <domain> [<subdomain>]"
fi
