#!/usr/bin/env bash
# install nginx on your web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
