#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
cat <<EOF | sudo tee /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        add_header X-Served-By "\$(hostname)";
    }

    location @oui_oui_baguette {
        default_type text/html;
        return 404 "Ceci n'est pas une page";
    }
}
EOF
sudo service nginx restart
