#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
backup_date=$(date +%d-%m-%Y)
mysqldump -u root -p"$1" backup.sql > backup.sql
tar -czvf "$backup_date.tar.gz" backup.sql
