#!/usr/bin/env bash
# manages manage_my_process


if [ $# == 0 ]
then
    echo "Usage: manage_my_process {start|stop|restart}"
fi
case $1 in
	start)
		sudo systemctl start /alx-system_engineering-devops/0x05-processes_and_signals/manage_my_process
		echo $$ >> /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		sudo systemctl stop /alx-system_engineering-devops/0x05-processes_and_signals/manage_my_process
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		sudo systemctl start /alx-system_engineering-devops/0x05-processes_and_signals/manage_my_process
		echo $$ >> /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
esac
