#!/usr/bin/env bash
# manages manage_my_process


if [ $# == 0 ]
then
    echo "Usage: manage_my_process {start|stop|restart}"
fi
case $1 in
	start)
		touch /var/run/my_process.pid
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pid=$(cat /var/run/my_process.pid)
		kill "$pid"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		pid=$(cat /var/run/my_process.pid)
		kill "$pid"
                rm /var/run/my_process.pid
		touch /var/run/my_process.pid
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
esac
