#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=':' read -r username _ gid user_info home shell
do
    group_name=$(getent group "$gid" | cut -d ':' -f 1)
    password=$(getent shadow "$username" | cut -d ':' -f 2)

    echo "The user $username is part of the $group_name gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

