#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
		i=$(( i +1 ))
	fi
	echo "Best School"
	i=$(( i +1 ))
done
