#!/usr/bin/env bash
# display hours from 0 to 12
# display minutes from 1 to 59

minutes=1
hour=0

while [ $hour -le 12 ]
do
	echo "Hour:" $hour
	while [ $minutes -le 59 ]
	do
		echo $minutes
		minutes=$(( minutes +1 ))
	done
	minutes=1
	hour=$(( hour +1 ))
done
