#!/usr/bin/env bash
# displays the:
# The content of the current directory
# In a list format

for i in *
do
	if [[ -f "$i" ]]
	then
        # Extract the part of the name after the first dash
        name_after_dash=${i#*-}

        # Print the extracted name
        echo "$name_after_dash"
    fi
done
