#!/bin/bash
# script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

server="100.25.30.218"
private_key="~/.ssh/school"
chmod 600 /root/.ssh/school
ssh -i "$private_key" "ubuntu@$server"
